#KEKW
ligne = input().lower()


ligne=ligne.replace("a","@")
ligne =ligne.replace('b','8')
ligne =ligne.replace('c','(')
ligne = ligne.replace('d','|)')
ligne= ligne.replace('e','3')
ligne= ligne.replace('f','#')
ligne = ligne.replace('g','6')
ligne = ligne.replace('h','[-]')
ligne =ligne.replace('i','|')
ligne =ligne.replace('j','_|')
ligne =ligne.replace('k','|<')
ligne =ligne.replace('l','1')
ligne =ligne.replace("m","[]\/[]")
ligne =ligne.replace('n',"[]\[]")
ligne =ligne.replace('o','0')
ligne =ligne.replace('p','|D')
ligne =ligne.replace('q','(,)')
ligne =ligne.replace('r','|Z')
ligne =ligne.replace('s','$')
ligne =ligne.replace('t',"']['")
ligne =ligne.replace('u','|_|')
ligne =ligne.replace('v',"\/")
ligne =ligne.replace('w',"\/\/")
ligne =ligne.replace('x','}{')
ligne =ligne.replace('y',"`/")
ligne =ligne.replace('z','2')

print(ligne)
